site_name: "PROTODUNE-METADEX: ProtoDUNE Metadata Exchange"
site_url: https://dune.github.io/protodune-metadex/

repo_url: https://github.com/DUNE/protodune-metadex
repo_name: DUNE/protodune-metadex

edit_uri: edit/main/docs/

extra_css:
  - stylesheets/extra.css

theme:
  features:
    - content.action.view
    - navigation.footer

  icon:
    admonition:
      diagram: fontawesome/solid/diagram-project

    logo: material/hub-outline

    repo: fontawesome/brands/github

  name: material

  palette:
    scheme: slate
    primary: deep orange

nav:
  - Introduction: "index.md"
  - Reference:
      - Architecture:
          - "Event Storming: Metadata Management": "architecture/event-storming.md"
      - API Reference:
          - interface.iov_controller: "reference/api/iov_controller.md"

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - tables

plugins:
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox
  - mkdocstrings
  - search
